#!/bin/bash -e

hash aws &>/dev/null || {
  (>&2 echo 'Error: AWS CLI not found on PATH');
  exit 1;
}

function usage {
  echo 'Usage:' $(basename "$0") '<encrypted-key> <plaintext>'
  echo '   or: echo <plaintext> |' $(basename "$0") '<encrypted-key>'
}

encrypted_key_base64=$1
value=$2

[ "$encrypted_key_base64" == "" ] && {
  (>&2 echo 'Error: Missing Encrypted Key');
  echo;
  usage;
  exit 1;
}

# if no <plaintext> is passed as an argument, try getting it from stdin if we're
# not interactive
[ "$value" == "" ] && [ ! -t 0 ] && {
  value=$(cat -);
}

[ "$value" == "" ] && {
  (>&2 echo 'Error: Missing Plaintext');
  echo;
  usage;
  exit 1;
}

key_base64=$(aws kms decrypt --ciphertext-blob fileb://<(echo -n "$encrypted_key_base64" | base64 --decode) --query Plaintext --output text)
# key_base64=$($(dirname -- "$0")/kms-decrypt "$encrypted_key_base64")
key=$(echo -n "$key_base64" | base64 --decode)
key_hex=$(echo -n "$key" | xxd -p | tr -d '\n')

iv=$(head -c16 /dev/urandom)
iv_base64=$(echo -n "$iv" | base64)
iv_hex=$(echo -n "$iv" | xxd -p | tr -d '\n')

[ "$DEBUG" == "true" ] && {
  echo 'key:';
  echo "$key_base64" | xargs echo 'base64:';
  echo "$key_hex" | xargs echo 'hex:';
  echo;

  echo 'iv:';
  echo "$iv_base64" | xargs echo 'base64:';
  echo "$iv_hex" | xargs echo 'hex:';
  echo;
}

encrypted_value=$(echo -n "$value" | openssl enc -aes-256-cbc -iv "$iv_hex" -K "$key_hex")
encrypted_value_base64=$(echo -n "$encrypted_value" | base64)
encrypted_value_hex=$(echo -n "$encrypted_value" | xxd -p | tr -d '\n')

final="$iv$encrypted_value"
final_base64=$(echo -n "$final" | base64)
final_hex=$(echo -n "$final" | xxd -p | tr -d '\n')

[ "$DEBUG" == "true" ] && {
  echo 'encrypted value:';
  echo "$encrypted_value_base64" | xargs echo 'base64:';
  echo "$encrypted_value_hex" | xargs echo 'hex:';
  echo;

  echo 'final:';
  echo "$final_base64" | xargs echo 'base64:';
  echo "$final_hex" | xargs echo 'hex:';
  echo;
}

echo -n "$final_base64"
